### ISSUE TITLE
The original format has changed

### ISSUE THREAD

**Issue by kyjdp** [msftrncs/PwshJSONtoPList#7]
test file: 
[Config.zip](https://github.com/msftrncs/PwshJSONtoPList/files/7133801/Config.zip)
_______________________________________________________________________________________________________________________________________
1.
befor:
```xml
<string></string>  
```
after:
```xml
				<dict>
				</dict>
```
_______________________________________________________________________________________________________________________________________
2. One line becomes two lines:

befor:
```xml
				<key>Name</key>
				<string>IONVMeFamily</string>
				<key>Find</key>
				<data>
				BgIAAEyNuAAQAABMiflIgeEA8P//SYmGGgEAAEmJjiIBAABBvAAQAABJKfQ=
				</data>
				<key>Replace</key>
				<data>
				BgIAAEyNuAACAABMiflIgeEA8P//SYmGGgEAAEmJjiIBAABBvAACAABJKfQ=
				</data>
```

after:
```xml
				<key>Name</key>
				<string>IONVMeFamily</string>
				<key>Find</key>
				<data>
					BgIAAEyNuAAQAABMiflIgeEA8P//SYmGGgEAAEmJjiIB
					AABBvAAQAABJKfQ=
				</data>
				<key>Replace</key>
				<data>
					BgIAAEyNuAACAABMiflIgeEA8P//SYmGGgEAAEmJjiIB
					AABBvAACAABJKfQ=
				</data>
```

![aaa](https://user-images.githubusercontent.com/6350504/132631187-4679167a-6729-490b-88c4-ba3e2fa5c68d.gif)

**Comment by msftrncs** [comment]
Hi, @kyjdp, 

Strictly speaking of a `<data>` block, the formatting is not specified formally.  Affectively, all white space characters are to be ignored, so the two examples are equivalent, as they differ only in format; even the indenting is different.

So I don't think there is an issue here.   Every tool that generates a PLIST might generate a slightly different formatting, while still being technically correct.

**Comment by msftrncs** [comment]
Notes:  
- Item 1, see https://github.com/msftrncs/PwshReadXmlPList/issues/7#
- Item 2, see #6.

**Comment by kyjdp** [comment]
> Hi, @kyjdp,
> 
> Strictly speaking of a `<data>` block, the formatting is not specified formally. Affectively, all white space characters are to be ignored, so the two examples are equivalent, as they differ only in format; even the indenting is different.
> 
> So I don't think there is an issue here. Every tool that generates a PLIST might generate a slightly different formatting, while still being technically correct.

@msftrncs 
Hello, thank you for your reply
Some values are broken into two lines,
Will this affect the actual effect? I haven't tested yet

**Comment by kyjdp** [comment]
@msftrncs 
Is there a way to set these values to one line?
![456](https://user-images.githubusercontent.com/6350504/133927508-a1110e30-5ccb-4c46-939b-b943a2d99783.png)

**Comment by msftrncs** [comment]
Because the `<data>` element is a BASE64 encoded value, spaces and line breaks have no impact, similar to how spaces between XML/HTML tags have no affect.  However an underlying principle in XML is general human readability, the wrapping of the `<data>` element serves to make it more friendly for human readers (even though BASE64 data really isn't very 'readable' per say).

Many of the PLIST examples I could find that had `<data>` elements had formatting using wrapping, and I also have experience with XML files (not PLIST type) that include megabytes of BASE64 'data' blocks also formatted with wrapping.  However, see #6, I will look in to some parameters that can control the formatting of the `<data>` element.
